### ISSUE TITLE
run nix-build has no response

### ISSUE THREAD

**Issue by semiwizard** [ymherklotz/verismith#71]
run `nix-build` in root of Verismith, there is not any info given.
after long time,
`nix-build fatal: unable to access transfer closed with outstanding read data remaining
error: program 'git' failed with exit code 128`

this is my env:
`Linux nixos 4.19.107 #1-NixOS SMP Fri Feb 28 15:39:01 UTC 2020 x86_64 GNU/Linux
nix (Nix) 2.3.3`

**Comment by ymherklotz** [comment]
Hmm that's interesting, I don't think I've ever encountered that. The master branch seems to build fine on [Ubuntu](https://travis-ci.com/github/ymherklotz/verismith/branches), Arch and MacOS though. I've actually never tried NixOS, and don't really know where to start debugging this. I pin a version of `<nixpkgs>` so that the build should always be reproducible.

Is that the only output that you get from `nix-build`?

Did you clone the repository, cd into it and run `nix-build`?

Do all other packages install fine on your system using `nix-build`?
