### ISSUE TITLE
Build fails: 'can't find include file HsTimeConfig.h' and other errors

### ISSUE THREAD

**Issue by yurivict** [ymherklotz/verismith#85]
[log](https://people.freebsd.org/~yuri/verismith-1.0.0.2-39-g2523998-failure.log)

hs-cabal-install-3.6.2.0_1
ghc-9.2.5
FreeBSD 13.1

**Comment by dwRchyngqxs** [comment]
The missing header is required because of the dependency on `time`. This issue might be related https://github.com/haskell/cabal/issues/5223 . I will try to reproduce and investigate the issue on my FreeBSD install.

**Comment by yurivict** [comment]
In particular, I tried to create a FreeBSD port for verismith and it fails to build.
Here is the shar with of the port: https://people.freebsd.org/~yuri/hs-verismith.shar

**Comment by yurivict** [comment]
https://github.com/ymherklotz/verismith/pull/86

**Comment by yurivict** [comment]
> This issue should be fixed by the maintainers of the time package, not us.

The last version 1.12.2 has it fixed. The proposed patch just moves the requirement to the version that works.

**Comment by dwRchyngqxs** [comment]
I investigated this bug on FreeBSD 13.1, using hs-cabal-install-3.6.2.0_2 and ghc-9.2.6 (latest available versions). Here are my results:

- Cloning the repo and running `cabal update` followed by `cabal build`, works fine, same with `cabal install`
- Using your shar archive that calls cabal with the bsd ports build system fails.
- Applying the change recommended by @arrowd in #86 and fixing your shar archive so that it uses time-1.12.2 works fine.

The way to solve this issue seems to be the following:

1. Fix your shar archive to use the latest time version and apply the change recommended by @arrowd in your pull request; We'll then merge your pull request.
2. Report the cabal build issue using the port build system to the port build system maintainers.

If there are still issues with that solution, please let us know.
